# Generated by Django 4.0.6 on 2022-07-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpage_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
