# Generated by Django 4.0.6 on 2022-07-28 08:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_people'),
        ('blog', '0006_blogpagetag_remove_blogpage_likes_blogpage_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLikers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_likers_relationship', to='blog.blogpage')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers_blog_relationship', to='home.people')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
