# Generated by Django 4.0.6 on 2022-07-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_people'),
        ('blog', '0008_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='creator',
            field=models.ForeignKey(default=1, help_text='The photo creator.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.people'),
            preserve_default=False,
        ),
    ]
