# Generated by Django 4.0.6 on 2022-07-29 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_albumpage_albumphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglikers',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers_blog_relationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
