# Generated by Django 4.0.6 on 2022-07-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0003_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feed',
            field=models.ForeignKey(blank=True, help_text='Feed Page to displays', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Feed Page'),
        ),
    ]
